export const menuList = [
  //   ----------------------Meat------------------------------
  {
    id: "Meat-001",
    typeEn: "Meat",
    typeAr: "لحم",
    nameEn: "Meat Serih",
    nameAr: "سيريه لحم",
    cal: "188",
    price: "20",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Meat Serih.jpg"],
  },
  {
    id: "Meat-002",
    typeEn: "Meat",
    typeAr: "لحم",
    nameEn: "Spicy Meat Serih",
    nameAr: "سيريه لحم حراق",
    cal: "192",
    price: "21",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Meat Serih.jpg"],
  },
  {
    id: "Meat-003",
    typeEn: "Meat",
    typeAr: "لحم",
    nameEn: "Half Meat Serih",
    nameAr: "نص سيريه لحم",
    cal: "94",
    price: "10",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Meat Serih.jpg"],
  },
  {
    id: "Meat-005",
    typeEn: "Meat",
    typeAr: "لحم",
    nameEn: "Meat Madfoon",
    nameAr: "مدفون لحم",
    cal: "265",
    price: "24",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Meat Madfoon.jpg"],
  },
  {
    id: "Meat-006",
    typeEn: "Meat",
    typeAr: "لحم",
    nameEn: "Spicy Meat Madfoon",
    nameAr: "مدفون لحم حراق",
    cal: "270",
    price: "25",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Meat Madfoon.jpg"],
  },
  {
    id: "Meat-007",
    typeEn: "Meat",
    typeAr: "لحم",
    nameEn: "Madfoun Meat with cheese",
    nameAr: "مدفون لحم جبن",
    cal: "304",
    price: "26",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Meat Madfoon.jpg"],
  },
  {
    id: "Meat-008",
    typeEn: "Meat",
    typeAr: "لحم",
    nameEn: "Spicy Madfoun Meat with Cheese",
    nameAr: "مدفون لحم جبن حراق",
    cal: "308",
    price: "27",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Meat Madfoon.jpg"],
  },
  {
    id: "Meat-004",
    typeEn: "Meat",
    typeAr: "لحم",
    nameEn: "Meat Serih Sandwich",
    nameAr: "ساندوتش سيريه لحم",
    cal: "200",
    price: "10",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Meat Serih Sandwich.jpg"],
  },
  //   ----------------------Chicken------------------------------
  {
    id: "Chicken-001",
    typeEn: "Chicken",
    typeAr: "دجاج",
    nameEn: "Chicken Serih",
    nameAr: "سيريه دجاج",
    cal: "145",
    price: "20",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Chicken Serih.jpg"],
  },
  {
    id: "Chicken-002",
    typeEn: "Chicken",
    typeAr: "دجاج",
    nameEn: "Spicy Chicken Serih",
    nameAr: "سيريه دجاج حراق",
    cal: "150",
    price: "21",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Chicken Serih.jpg"],
  },
  {
    id: "Chicken-004",
    typeEn: "Chicken",
    typeAr: "دجاج",
    nameEn: "Half Chicken Serih",
    nameAr: "نص سيريه دجاج",
    cal: "73",
    price: "10",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Chicken Serih.jpg"],
  },
  {
    id: "Chicken-005",
    typeEn: "Chicken",
    typeAr: "دجاج",
    nameEn: "Madfoon Chicken",
    nameAr: "مدفون دجاج",
    cal: "282",
    price: "24",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Madfoon Chicken.jpg"],
  },
  {
    id: "Chicken-006",
    typeEn: "Chicken",
    typeAr: "دجاج",
    nameEn: "Spicy Madfoon Chicken",
    nameAr: "مدفون دجاج حراق",
    cal: "287",
    price: "25",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Madfoon Chicken.jpg"],
  },
  {
    id: "Chicken-007",
    typeEn: "Chicken",
    typeAr: "دجاج",
    nameEn: "Madfoon Chicken with Cheese",
    nameAr: "مدفون دجاج جبن",
    cal: "304",
    price: "26",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Madfoon Chicken.jpg"],
  },
  {
    id: "Chicken-008",
    typeEn: "Chicken",
    typeAr: "دجاج",
    nameEn: "Spicy Madfoon Chicken with Cheese",
    nameAr: "مدفون دجاج جبن حراق",
    cal: "309",
    price: "27",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Madfoon Chicken.jpg"],
  },
  {
    id: "Chicken-003",
    typeEn: "Chicken",
    typeAr: "دجاج",
    nameEn: "Chicken Serih Sandwich",
    nameAr: "ساندوتش سيريه دجاج",
    cal: "150",
    price: "10",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Chicken Serih Sandwich.jpg"],
  },
  //   ----------------------Fish------------------------------
  {
    id: "Fish-001",
    typeEn: "Fish",
    typeAr: "سمك",
    nameEn: "Fish Serih",
    nameAr: "سيريه سمك",
    cal: "136",
    price: "22",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Fish Serih.jpg"],
  },
  {
    id: "Fish-002",
    typeEn: "Fish",
    typeAr: "سمك",
    nameEn: "Spicy Fish Serih",
    nameAr: "سيريه سمك حراق",
    cal: "140",
    price: "23",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Fish Serih.jpg"],
  },
  {
    id: "Fish-004",
    typeEn: "Fish",
    typeAr: "سمك",
    nameEn: "Half Fish Serih",
    nameAr: "نص سيريه سمك",
    cal: "68",
    price: "11",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Fish Serih.jpg"],
  },
  {
    id: "Fish-005",
    typeEn: "Fish",
    typeAr: "سمك",
    nameEn: "Madfoon Fish",
    nameAr: "مدفون سمك",
    cal: "190",
    price: "25",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Madfoon Fish.jpg"],
  },
  {
    id: "Fish-006",
    typeEn: "Fish",
    typeAr: "سمك",
    nameEn: "Spicy Madfoon Fish",
    nameAr: "مدفون سمك حراق",
    cal: "195",
    price: "26",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Madfoon Fish.jpg"],
  },
  {
    id: "Fish-007",
    typeEn: "Fish",
    typeAr: "سمك",
    nameEn: "Madfoon Fish with Cheese",
    nameAr: "مدفون سمك جبن",
    cal: "230",
    price: "28",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Madfoon Fish.jpg"],
  },
  {
    id: "Fish-008",
    typeEn: "Fish",
    typeAr: "سمك",
    nameEn: "Spicy Madfoon Fish with Cheese",
    nameAr: "مدفون سمك جبن حراق",
    cal: "235",
    price: "29",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Madfoon Fish.jpg"],
  },
  {
    id: "Fish-003",
    typeEn: "Fish",
    typeAr: "سمك",
    nameEn: "Fish Serih Sandwich",
    nameAr: "ساندوتش سيريه سمك",
    cal: "40",
    price: "11",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Fish Serih Sandwich.jpg"],
  },
  //   ----------------------Shrimp------------------------------
  {
    id: "Shrimp-001",
    typeEn: "Shrimp",
    typeAr: "جمبري",
    nameEn: "Shrimp Serih",
    nameAr: "سيريه جمبري",
    cal: "110",
    price: "25",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Shrimp Serih.jpg"],
  },
  {
    id: "Shrimp-002",
    typeEn: "Shrimp",
    typeAr: "جمبري",
    nameEn: "Spicy Shrimp Serih",
    nameAr: "سيريه جمبري حراق",
    cal: "117",
    price: "26",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Shrimp Serih.jpg"],
  },
  {
    id: "Shrimp-004",
    typeEn: "Shrimp",
    typeAr: "جمبري",
    nameEn: "Half Shrimp Serih",
    nameAr: "نص سيريه جمبري",
    cal: "55",
    price: "12",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["../../images/list1/01.png"],
  },
  {
    id: "Shrimp-005",
    typeEn: "Shrimp",
    typeAr: "جمبري",
    nameEn: "Madfoon Shrimp",
    nameAr: "مدفون جمبري",
    cal: "140",
    price: "27",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Madfoon Shrimp.jpg"],
  },
  {
    id: "Shrimp-006",
    typeEn: "Shrimp",
    typeAr: "جمبري",
    nameEn: "Spicy Madfoon Shrimp",
    nameAr: "مدفون جمبري حراق",
    cal: "145",
    price: "28",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Madfoon Shrimp.jpg"],
  },
  {
    id: "Shrimp-007",
    typeEn: "Shrimp",
    typeAr: "جمبري",
    nameEn: "Madfoon Shrimp with Cheese",
    nameAr: "مدفون جمبري جبن",
    cal: "150",
    price: "30",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Madfoon Shrimp.jpg"],
  },
  {
    id: "Shrimp-008",
    typeEn: "Shrimp",
    typeAr: "جمبري",
    nameEn: "Spicy Madfoon Shrimp with Cheese",
    nameAr: "مدفون جمبري جبن حراق",
    cal: "180",
    price: "31",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Madfoon Shrimp.jpg"],
  },
  {
    id: "Shrimp-003",
    typeEn: "Shrimp",
    typeAr: "جمبري",
    nameEn: "Shrimp Serih Sandwich",
    nameAr: "ساندوتش جمبري",
    cal: "130",
    price: "12",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Shrimp Serih Sandwich.jpg"],
  },
  {
    id: "Shrimp-009",
    typeEn: "Shrimp",
    typeAr: "جمبري",
    nameEn: "Madfoon Azoz",
    nameAr: "مدفون عزوز",
    cal: "140",
    price: "30",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Madfoon Shrimp.jpg"],
  },
  {
    id: "Shrimp-010",
    typeEn: "Shrimp",
    typeAr: "جمبري",
    nameEn: "Madfoon Azoz with Cheese",
    nameAr: "مدفون عزوز جبن",
    cal: "150",
    price: "32",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Madfoon Shrimp.jpg"],
  },
  //   ----------------------Grill------------------------------
  {
    id: "Grill-001",
    typeEn: "Grill",
    typeAr: "شيه",
    nameEn: "Meat Grill",
    nameAr: "شية لحم",
    cal: "262",
    price: "25",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Grill Serih.jpg"],
  },
  {
    id: "Grill-002",
    typeEn: "Grill",
    typeAr: "شيه",
    nameEn: "Spicy Grill Serih",
    nameAr: "شية لحم حراق",
    cal: "270",
    price: "26",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Grill Serih.jpg"],
  },
  {
    id: "Grill-003",
    typeEn: "Grill",
    typeAr: "شيه",
    nameEn: "Grill Serih Sandwich",
    nameAr: "ساندوتش سيريه شيه",
    cal: "270",
    price: "8",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Grill Serih.jpg"],
  },
  {
    id: "Grill-004",
    typeEn: "Grill",
    typeAr: "شيه",
    nameEn: "Madfoon Meat Grill",
    nameAr: "مدفون شية لحم",
    cal: "290",
    price: "27",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Madfoon Grill.jpg"],
  },
  {
    id: "Grill-005",
    typeEn: "Grill",
    typeAr: "شيه",
    nameEn: "Madfoon Grill with Cheese",
    nameAr: "شيه مدفون جبن",
    cal: "320",
    price: "29",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Madfoon Grill.jpg"],
  },
  {
    id: "Grill-006",
    typeEn: "Grill",
    typeAr: "شيه",
    nameEn: "Spicy Madfoon Grill with Cheese",
    nameAr: "شيه مدفون جبن حراق",
    cal: "380",
    price: "30",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Madfoon Grill.jpg"],
  },
  {
    id: "Grill-007",
    typeEn: "Grill",
    typeAr: "شيه",
    nameEn: "Mixed Beans",
    nameAr: "فول مصلح",
    cal: "100",
    price: "8",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["01.png"],
  },
  {
    id: "Grill-008",
    typeEn: "Grill",
    typeAr: "شيه",
    nameEn: "Lentil",
    nameAr: "عدس",
    cal: "677",
    price: "7",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["01.png"],
  },
  //   ----------------------Drinks------------------------------
  {
    id: "Drinks-001",
    typeEn: "Drinks",
    typeAr: "المشروبات",
    nameEn: "J juice",
    nameAr: "مشروب جي",
    cal: "150",
    price: "6",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["juice.jpg"],
  },
  {
    id: "Drinks-002",
    typeEn: "Drinks",
    typeAr: "المشروبات",
    nameEn: "1 liter J juice",
    nameAr: "عصير جي لتر",
    cal: "",
    price: "17",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["juice.jpg"],
  },
  {
    id: "Drinks-003",
    typeEn: "Drinks",
    typeAr: "المشروبات",
    nameEn: "1.5 liter J juice",
    nameAr: "عصير جي لتر ونص",
    cal: "",
    price: "23",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["juice.jpg"],
  },
  {
    id: "Drinks-004",
    typeEn: "Drinks",
    typeAr: "المشروبات",
    nameEn: "Hibiscus juice",
    nameAr: "مشروب كركديه",
    cal: "",
    price: "4",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Hibiscus juice.jpg"],
  },
  {
    id: "Drinks-005",
    typeEn: "Drinks",
    typeAr: "المشروبات",
    nameEn: "1 litre Hibiscus juice",
    nameAr: "عصير كركديه لتر",
    cal: "75",
    price: "15",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Hibiscus juice.jpg"],
  },
  {
    id: "Drinks-006",
    typeEn: "Drinks",
    typeAr: "المشروبات",
    nameEn: "1.5 litre Hibiscus juice",
    nameAr: "عصير كركديه لتر ونص",
    cal: "",
    price: "20",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Hibiscus juice.jpg"],
  },
  {
    id: "Drinks-007",
    typeEn: "Drinks",
    typeAr: "المشروبات",
    nameEn: "Fro Fro juice",
    nameAr: "مشروب فرو فرو",
    cal: "",
    price: "6",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Smoking drink.jpg"],
  },

  {
    id: "Drinks-008",
    typeEn: "Drinks",
    typeAr: "المشروبات",
    nameEn: "1 litre Four four juice",
    nameAr: "عصير فور فور لتر",
    cal: "",
    price: "17",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Smoking drink.jpg"],
  },
  {
    id: "Drinks-009",
    typeEn: "Drinks",
    typeAr: "المشروبات",
    nameEn: "1.5 litre Four four juice",
    nameAr: "عصير فور فور لتر ونص",
    cal: "",
    price: "24",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["Smoking drink.jpg"],
  },
  {
    id: "Drinks-010",
    typeEn: "Drinks",
    typeAr: "المشروبات",
    nameEn: "Sodas",
    nameAr: "مشروبات غازية",
    cal: "300",
    price: "3",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["../../images/list/pepsi.jpg"],
  },
  {
    id: "Drinks-011",
    typeEn: "Drinks",
    typeAr: "المشروبات",
    nameEn: "Water",
    nameAr: "ماء",
    cal: "",
    price: "1",
    currencyAr: "ريال",
    currencyEn: "Sr",
    imgs: ["water4.jpg"],
  },
]
